# Generated by Django 4.2.6 on 2023-10-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvdata',
            name='employee_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='csvdata',
            name='file_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='timereport',
            name='employee_id',
            field=models.IntegerField(),
        ),
    ]
